export const COUNTRIES = [
  { name: 'Afghanistan', flag: 'af', code: 'af' },
  { name: 'Albania', flag: 'al', code: 'al' },
  { name: 'Algeria', flag: 'dz', code: 'dz' },
  { name: 'Andorra', flag: 'ad', code: 'ad' },
  { name: 'Angola', flag: 'ao', code: 'ao' },
  { name: 'Argentina', flag: 'ar', code: 'ar' },
  { name: 'Armenia', flag: 'am', code: 'am' },
  { name: 'Australia', flag: 'au', code: 'au' },
  { name: 'Austria', flag: 'at', code: 'at' },
  { name: 'Azerbaijan', flag: 'az', code: 'az' },
  { name: 'Bahamas', flag: 'bs', code: 'bs' },
  { name: 'Bahrain', flag: 'bh', code: 'bh' },
  { name: 'Bangladesh', flag: 'bd', code: 'bd' },
  { name: 'Barbados', flag: 'bb', code: 'bb' },
  { name: 'Belarus', flag: 'by', code: 'by' },
  { name: 'Belgium', flag: 'be', code: 'be' },
  { name: 'Belize', flag: 'bz', code: 'bz' },
  { name: 'Benin', flag: 'bj', code: 'bj' },
  { name: 'Bhutan', flag: 'bt', code: 'bt' },
  { name: 'Bolivia', flag: 'bo', code: 'bo' },
  { name: 'Bosnia and Herzegovina', flag: 'ba', code: 'ba' },
  { name: 'Botswana', flag: 'bw', code: 'bw' },
  { name: 'Brazil', flag: 'br', code: 'br' },
  { name: 'Brunei', flag: 'bn', code: 'bn' },
  { name: 'Bulgaria', flag: 'bg', code: 'bg' },
  { name: 'Burkina Faso', flag: 'bf', code: 'bf' },
  { name: 'Burundi', flag: 'bi', code: 'bi' },
  { name: 'Cambodia', flag: 'kh', code: 'kh' },
  { name: 'Cameroon', flag: 'cm', code: 'cm' },
  { name: 'Canada', flag: 'ca', code: 'ca' },
  { name: 'Cape Verde', flag: 'cv', code: 'cv' },
  { name: 'Central African Republic', flag: 'cf', code: 'cf' },
  { name: 'Chad', flag: 'td', code: 'td' },
  { name: 'Chile', flag: 'cl', code: 'cl' },
  { name: 'China', flag: 'cn', code: 'cn' },
  { name: 'Colombia', flag: 'co', code: 'co' },
  { name: 'Comoros', flag: 'km', code: 'km' },
  { name: 'Costa Rica', flag: 'cr', code: 'cr' },
  { name: 'Croatia', flag: 'hr', code: 'hr' },
  { name: 'Cuba', flag: 'cu', code: 'cu' },
  { name: 'Cyprus', flag: 'cy', code: 'cy' },
  { name: 'Czech Republic', flag: 'cz', code: 'cz' },
  { name: 'Denmark', flag: 'dk', code: 'dk' },
  { name: 'Djibouti', flag: 'dj', code: 'dj' },
  { name: 'Dominican Republic', flag: 'do', code: 'do' },
  { name: 'Ecuador', flag: 'ec', code: 'ec' },
  { name: 'Egypt', flag: 'eg', code: 'eg' },
  { name: 'El Salvador', flag: 'sv', code: 'sv' },
  { name: 'England', flag: 'gb-eng', code: 'gb-eng' },
  { name: 'Equatorial Guinea', flag: 'gq', code: 'gq' },
  { name: 'Eritrea', flag: 'er', code: 'er' },
  { name: 'Estonia', flag: 'ee', code: 'ee' },
  { name: 'Eswatini', flag: 'sz', code: 'sz' },
  { name: 'Ethiopia', flag: 'et', code: 'et' },
  { name: 'Fiji', flag: 'fj', code: 'fj' },
  { name: 'Finland', flag: 'fi', code: 'fi' },
  { name: 'France', flag: 'fr', code: 'fr' },
  { name: 'Gabon', flag: 'ga', code: 'ga' },
  { name: 'Gambia', flag: 'gm', code: 'gm' },
  { name: 'Georgia', flag: 'ge', code: 'ge' },
  { name: 'Germany', flag: 'de', code: 'de' },
  { name: 'Ghana', flag: 'gh', code: 'gh' },
  { name: 'Greece', flag: 'gr', code: 'gr' },
  { name: 'Guatemala', flag: 'gt', code: 'gt' },
  { name: 'Guinea', flag: 'gn', code: 'gn' },
  { name: 'Guyana', flag: 'gy', code: 'gy' },
  { name: 'Haiti', flag: 'ht', code: 'ht' },
  { name: 'Honduras', flag: 'hn', code: 'hn' },
  { name: 'Hungary', flag: 'hu', code: 'hu' },
  { name: 'Iceland', flag: 'is', code: 'is' },
  { name: 'India', flag: 'in', code: 'in' },
  { name: 'Indonesia', flag: 'id', code: 'id' },
  { name: 'Iran', flag: 'ir', code: 'ir' },
  { name: 'Iraq', flag: 'iq', code: 'iq' },
  { name: 'Ireland', flag: 'ie', code: 'ie' },
  { name: 'Israel', flag: 'il', code: 'il' },
  { name: 'Italy', flag: 'it', code: 'it' },
  { name: 'Ivory Coast', flag: 'ci', code: 'ci' },
  { name: 'Jamaica', flag: 'jm', code: 'jm' },
  { name: 'Japan', flag: 'jp', code: 'jp' },
  { name: 'Jordan', flag: 'jo', code: 'jo' },
  { name: 'Kazakhstan', flag: 'kz', code: 'kz' },
  { name: 'Kenya', flag: 'ke', code: 'ke' },
  { name: 'Kosovo', flag: 'xk', code: 'xk' },
  { name: 'Kuwait', flag: 'kw', code: 'kw' },
  { name: 'Kyrgyzstan', flag: 'kg', code: 'kg' },
  { name: 'Laos', flag: 'la', code: 'la' },
  { name: 'Latvia', flag: 'lv', code: 'lv' },
  { name: 'Lebanon', flag: 'lb', code: 'lb' },
  { name: 'Liberia', flag: 'lr', code: 'lr' },
  { name: 'Libya', flag: 'ly', code: 'ly' },
  { name: 'Lithuania', flag: 'lt', code: 'lt' },
  { name: 'Luxembourg', flag: 'lu', code: 'lu' },
  { name: 'Madagascar', flag: 'mg', code: 'mg' },
  { name: 'Malawi', flag: 'mw', code: 'mw' },
  { name: 'Malaysia', flag: 'my', code: 'my' },
  { name: 'Mali', flag: 'ml', code: 'ml' },
  { name: 'Malta', flag: 'mt', code: 'mt' },
  { name: 'Mauritania', flag: 'mr', code: 'mr' },
  { name: 'Mexico', flag: 'mx', code: 'mx' },
  { name: 'Moldova', flag: 'md', code: 'md' },
  { name: 'Monaco', flag: 'mc', code: 'mc' },
  { name: 'Mongolia', flag: 'mn', code: 'mn' },
  { name: 'Montenegro', flag: 'me', code: 'me' },
  { name: 'Morocco', flag: 'ma', code: 'ma' },
  { name: 'Mozambique', flag: 'mz', code: 'mz' },
  { name: 'Myanmar', flag: 'mm', code: 'mm' },
  { name: 'Namibia', flag: 'na', code: 'na' },
  { name: 'Nepal', flag: 'np', code: 'np' },
  { name: 'Netherlands', flag: 'nl', code: 'nl' },
  { name: 'New Zealand', flag: 'nz', code: 'nz' },
  { name: 'Nicaragua', flag: 'ni', code: 'ni' },
  { name: 'Niger', flag: 'ne', code: 'ne' },
  { name: 'Nigeria', flag: 'ng', code: 'ng' },
  { name: 'North Korea', flag: 'kp', code: 'kp' },
  { name: 'North Macedonia', flag: 'mk', code: 'mk' },
  { name: 'Northern Ireland', flag: 'gb-nir', code: 'gb-nir' },
  { name: 'Norway', flag: 'no', code: 'no' },
  { name: 'Oman', flag: 'om', code: 'om' },
  { name: 'Pakistan', flag: 'pk', code: 'pk' },
  { name: 'Palestine', flag: 'ps', code: 'ps' },
  { name: 'Panama', flag: 'pa', code: 'pa' },
  { name: 'Paraguay', flag: 'py', code: 'py' },
  { name: 'Peru', flag: 'pe', code: 'pe' },
  { name: 'Philippines', flag: 'ph', code: 'ph' },
  { name: 'Poland', flag: 'pl', code: 'pl' },
  { name: 'Portugal', flag: 'pt', code: 'pt' },
  { name: 'Qatar', flag: 'qa', code: 'qa' },
  { name: 'Romania', flag: 'ro', code: 'ro' },
  { name: 'Russia', flag: 'ru', code: 'ru' },
  { name: 'Rwanda', flag: 'rw', code: 'rw' },
  { name: 'Saudi Arabia', flag: 'sa', code: 'sa' },
  { name: 'Scotland', flag: 'gb-sct', code: 'gb-sct' },
  { name: 'Senegal', flag: 'sn', code: 'sn' },
  { name: 'Serbia', flag: 'rs', code: 'rs' },
  { name: 'Singapore', flag: 'sg', code: 'sg' },
  { name: 'Slovakia', flag: 'sk', code: 'sk' },
  { name: 'Slovenia', flag: 'si', code: 'si' },
  { name: 'Somalia', flag: 'so', code: 'so' },
  { name: 'South Africa', flag: 'za', code: 'za' },
  { name: 'South Korea', flag: 'kr', code: 'kr' },
  { name: 'Spain', flag: 'es', code: 'es' },
  { name: 'Sri Lanka', flag: 'lk', code: 'lk' },
  { name: 'Sudan', flag: 'sd', code: 'sd' },
  { name: 'Sweden', flag: 'se', code: 'se' },
  { name: 'Switzerland', flag: 'ch', code: 'ch' },
  { name: 'Syria', flag: 'sy', code: 'sy' },
  { name: 'Taiwan', flag: 'tw', code: 'tw' },
  { name: 'Tajikistan', flag: 'tj', code: 'tj' },
  { name: 'Tanzania', flag: 'tz', code: 'tz' },
  { name: 'Thailand', flag: 'th', code: 'th' },
  { name: 'Togo', flag: 'tg', code: 'tg' },
  { name: 'Tunisia', flag: 'tn', code: 'tn' },
  { name: 'Turkey', flag: 'tr', code: 'tr' },
  { name: 'Turkmenistan', flag: 'tm', code: 'tm' },
  { name: 'Uganda', flag: 'ug', code: 'ug' },
  { name: 'Ukraine', flag: 'ua', code: 'ua' },
  { name: 'United Arab Emirates', flag: 'ae', code: 'ae' },
  { name: 'United Kingdom', flag: 'gb', code: 'gb' },
  { name: 'United States', flag: 'us', code: 'us' },
  { name: 'Uruguay', flag: 'uy', code: 'uy' },
  { name: 'Uzbekistan', flag: 'uz', code: 'uz' },
  { name: 'Venezuela', flag: 've', code: 've' },
  { name: 'Vietnam', flag: 'vn', code: 'vn' },
  { name: 'Wales', flag: 'gb-wls', code: 'gb-wls' },
  { name: 'Yemen', flag: 'ye', code: 'ye' },
  { name: 'Zambia', flag: 'zm', code: 'zm' },
  { name: 'Zimbabwe', flag: 'zw', code: 'zw' },
];
